"""Tests for the Gate 10 context-preparation workflow tools."""

from unittest.mock import MagicMock

import pytest

from src.evidence_models import ApplicationScopedEvidence
from src.workflow_tools import WorkflowTools


@pytest.fixture
def backend():
    return MagicMock()


@pytest.fixture
def workflow_tools(backend):
    return WorkflowTools(backend=backend, orchestrator=MagicMock())


def test_start_workflow_returns_frontend_prompt_without_backend_calls(
    workflow_tools,
    backend,
):
    result = workflow_tools.start_job_application_workflow(
        job_jd="Company: Acme Corp\nPosition: Senior Software Engineer\nPython and AWS required.",
        application_id="app-001",
        user_name="Alice",
    )

    assert result["ok"] is True
    assert result["application_id"] == "app-001"
    assert result["workflow_started"] is True
    assert result["initial_stage"] == "jd_analysis"
    assert result["next_action"] == "generate_clarifying_questions"
    assert "Alice" in result["system_prompt"]
    assert "Acme" in result["system_prompt"]
    assert "Senior Software Engineer" in result["system_prompt"]
    assert "Python and AWS required" in result["system_prompt"]
    backend.assert_not_called()


def test_start_workflow_rejects_empty_job_description(workflow_tools):
    result = workflow_tools.start_job_application_workflow(
        job_jd="  ",
        application_id="app-001",
        user_name="Alice",
    )

    assert result == {
        "ok": False,
        "error": "Job description is required",
        "application_id": "app-001",
    }


@pytest.mark.parametrize(
    ("jd", "company", "role"),
    [
        (
            "Company: Acme Corp\nPosition: Senior Software Engineer",
            "Acme",
            "Senior Software Engineer",
        ),
        (
            "About Example Ltd\nRole: Account Director",
            "Example",
            "Account Director",
        ),
    ],
)
def test_job_description_metadata_extraction(jd, company, role):
    tools = WorkflowTools()

    assert tools._extract_company_name(jd) == company
    assert tools._extract_role_title(jd) == role


def test_generate_clarifying_questions_returns_context_prompt(workflow_tools):
    result = workflow_tools.generate_clarifying_questions(
        application_id="app-002",
        jd_content="Company: Example Ltd\nRole: Account Director",
    )

    assert result["ok"] is True
    assert result["application_id"] == "app-002"
    assert result["questions"] == []
    assert result["question_count"] == 5
    assert result["next_action"] == "answer_clarifying_questions"
    assert "Example" in result["system_prompt"]
    assert "Account Director" in result["system_prompt"]


def test_generate_clarifying_questions_reports_invalid_content(workflow_tools):
    result = workflow_tools.generate_clarifying_questions("app-002", None)

    assert result["ok"] is False
    assert result["error"]


def test_answer_clarifying_questions_persists_only_nonempty_answers(
    workflow_tools,
    backend,
):
    result = workflow_tools.answer_clarifying_questions(
        application_id="app-003",
        answers={"leadership": "Led a team of five.", "cloud": "  ", "skip": None},
    )

    assert result == {
        "ok": True,
        "evidence_stored": 1,
        "next_action": "generate_cv_draft",
    }
    backend.save_application_evidence.assert_called_once()
    evidence = backend.save_application_evidence.call_args.args[0]
    assert isinstance(evidence, ApplicationScopedEvidence)
    assert evidence.application_id == "app-003"
    assert evidence.evidence_id == "app-003-leadership"
    assert evidence.response == "Led a team of five."
    assert evidence.source == "user_input"
    assert evidence.added_by_agent is False


def test_answer_clarifying_questions_rejects_empty_answers(workflow_tools):
    assert workflow_tools.answer_clarifying_questions("app-003", {}) == {
        "ok": False,
        "error": "answers dict is required",
    }


def test_answer_clarifying_questions_works_without_backend():
    tools = WorkflowTools(backend=None)

    result = tools.answer_clarifying_questions("app-004", {"scope": "APAC"})

    assert result["ok"] is True
    assert result["evidence_stored"] == 1


def test_generate_cv_draft_uses_base_cv_and_evidence(tmp_path, monkeypatch):
    base_cv = tmp_path / "base_cv.md"
    base_cv.write_text("# Base CV\n\nVerified experience.", encoding="utf-8")
    monkeypatch.setenv("JOB_APP_BASE_CV_PATH", str(base_cv))
    tools = WorkflowTools()

    result = tools.generate_cv_draft(
        application_id="app-005",
        jd_content="Position: Sales Director",
        evidence_items=["Expanded a verified regional account."],
    )

    assert result["ok"] is True
    assert result["cv_draft"] == "Draft to be generated by frontend LLM."
    assert result["draft_version"] == 1
    assert "# Base CV" in result["system_prompt"]
    assert "Expanded a verified regional account." in result["system_prompt"]
    assert "Sales Director" in result["system_prompt"]


def test_generate_cv_draft_rejects_missing_context(workflow_tools):
    assert workflow_tools.generate_cv_draft("app-005", "", []) == {
        "ok": False,
        "error": "missing cv data",
    }


def test_revise_cv_returns_frontend_prompt(workflow_tools):
    result = workflow_tools.revise_cv(
        application_id="app-006",
        cv_draft="# Current CV",
        revision_notes="Tighten the summary without changing metrics.",
    )

    assert result["ok"] is True
    assert result["revised_cv"] == "Revision to be generated by frontend LLM."
    assert result["revision_version"] == 2
    assert result["next_action"] == "confirm_cv"
    assert "without changing metrics" in result["system_prompt"]


def test_revise_cv_rejects_missing_notes(workflow_tools):
    assert workflow_tools.revise_cv("app-006", "# Current CV", "") == {
        "ok": False,
        "error": "missing revision notes",
    }


@pytest.mark.parametrize(
    ("confirmed", "next_action", "saved_path"),
    [
        (True, "proceed_to_submit", "/tmp/cv_app-007.md"),
        (False, "revise_again", None),
    ],
)
def test_confirm_cv_preserves_explicit_user_decision(
    workflow_tools,
    confirmed,
    next_action,
    saved_path,
):
    result = workflow_tools.confirm_cv("app-007", "# Final CV", confirmed)

    assert result == {
        "ok": True,
        "confirmed": confirmed,
        "next_action": next_action,
        "saved_path": saved_path,
    }


@pytest.mark.parametrize(
    ("count", "stage", "progress"),
    [
        (0, "jd_analysis", 10),
        (1, "evidence_gathering", 30),
        (4, "cv_generation", 60),
        (8, "cv_refinement", 85),
    ],
)
def test_get_workflow_state_reflects_evidence_count(
    workflow_tools,
    backend,
    count,
    stage,
    progress,
):
    backend.get_evidence_by_application.return_value = [object()] * count

    result = workflow_tools.get_workflow_state("app-008")

    assert result["ok"] is True
    assert result["application_id"] == "app-008"
    assert result["evidence_count"] == count
    assert result["current_stage"] == stage
    assert result["progress_percent"] == progress


def test_get_workflow_state_falls_back_to_cv_evidence(backend):
    backend.get_evidence_by_application.return_value = []
    backend.get_evidence_by_cv_id.return_value = [object(), object()]
    tools = WorkflowTools(backend=backend)

    result = tools.get_workflow_state("app-009")

    assert result["evidence_count"] == 2
    backend.get_evidence_by_cv_id.assert_called_once_with("app-009")


def test_get_workflow_state_returns_structured_error(backend):
    backend.get_evidence_by_application.side_effect = RuntimeError("backend unavailable")
    tools = WorkflowTools(backend=backend)

    result = tools.get_workflow_state("app-010")

    assert result == {"ok": False, "error": "backend unavailable"}
